apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: fakeshop
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13.16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: fakeshop
            - name: POSTGRES_USER
              value: fakeshop
            - name: POSTGRES_PASSWORD
              value: Pg1234
